services:
  http_sphere:
    image: bromanonld/route-sphere
    ports:
      - "8080:8080"
    environment:
      # The name of the environment in which the
      # server is running. This is used to load
      # the correct environment from the `environments.yaml`
      #
      ROUTE_SPHERE_ENVIRONMENT_NAME: "default"
