configurations:
  - name: default
    providers:
      - type: directory
        watch: true
        directory: "/home/development/Desktop/learning-go/route-sphere/.docker/configuration/dynamic"
    entryPoints:
      - name: "web"
        address: ":1234"
      - name: "websecure"
        address: ":443"
    domains: []
    routers: []
    services: []
